export const SEND_CONTACT = 'SEND_CONTACT';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAILURE = 'SEND_CONTACT_FAILURE';
export const INIT_CONTACT_STATUS = 'INIT_CONTACT_STATUS';
