export const LOAD_CUSTOMER_ESTIMATES = 'LOAD_CUSTOMER_ESTIMATES';
export const LOAD_CUSTOMER_ESTIMATES_SUCCESS = 'LOAD_CUSTOMER_ESTIMATES_SUCCESS';
export const LOAD_CUSTOMER_ESTIMATES_FAILURE = 'LOAD_CUSTOMER_ESTIMATES_FAILURE';

