export const CREATE_NEW_ESTIMATE = 'CREATE_NEW_ESTIMATE';
export const CREATE_NEW_ESTIMATE_SUCCESS = 'CREATE_NEW_ESTIMATE_SUCCESS';
export const CREATE_NEW_ESTIMATE_FAILURE = 'CREATE_NEW_ESTIMATE_FAILURE';

export const CREATE_NEW_INFO = 'CREATE_NEW_INFO';
export const CREATE_NEW_INFO_SUCCESS = 'CREATE_NEW_INFO_SUCCESS';
export const CREATE_NEW_INFO_FAILURE = 'CREATE_NEW_INFO_FAILURE';

export const CREATE_NEW_JOB = 'CREATE_NEW_JOB';
export const CREATE_NEW_JOB_SUCCESS = 'CREATE_NEW_JOB_SUCCESS';
export const CREATE_NEW_JOB_FAILURE = 'CREATE_NEW_JOB_FAILURE';

export const CREATE_NEW_HOME = 'CREATE_NEW_HOME';
export const CREATE_NEW_HOME_SUCCESS = 'CREATE_NEW_HOME_SUCCESS';
export const CREATE_NEW_HOME_FAILURE = 'CREATE_NEW_HOME_FAILURE';

