export const LOAD_CUSTOMER_ESTIMATE_DETAIL = 'LOAD_CUSTOMER_ESTIMATE_DETAIL';
export const LOAD_CUSTOMER_ESTIMATE_DETAIL_SUCCESS = 'LOAD_CUSTOMER_ESTIMATE_DETAIL_SUCCESS';
export const LOAD_CUSTOMER_ESTIMATE_DETAIL_FAILURE = 'LOAD_CUSTOMER_ESTIMATE_DETAIL_FAILURE';

export const PAYMENT_ESTIMATE = 'PAYMENT_ESTIMATE';
export const PAYMENT_ESTIMATE_SUCCESS = 'PAYMENT_ESTIMATE_SUCCESS';
export const PAYMENT_ESTIMATE_FAILURE = 'PAYMENT_ESTIMATE_FAILURE';


