export const GET_PAYMENT_INFO = 'GET_PAYMENT_INFO';
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS';
export const GET_PAYMENT_INFO_FAILURE = 'LOAD_PROFILE_FAILURE';

export const PAYMENT = 'PAYMENT';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';

export const INVOICE_PAYMENT = 'INVOICE_PAYMENT';
export const INVOICE_PAYMENT_SUCCESS = 'INVOICE_PAYMENT_SUCCESS';
export const INVOICE_PAYMENT_FAILURE = 'INVOICE_PAYMENT_FAILURE';

export const GET_INVOICE_INFO = 'GET_INVOICE_INFO';
export const GET_INVOICE_INFO_SUCCESS = 'GET_INVOICE_INFO_SUCCESS';
export const GET_INVOICE_INFO_FAILURE = 'GET_INVOICE_INFO_FAILURE';
