require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'TinaMaids' do
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'
  pod 'XCDYouTubeKit', '~> 2.8'


  target 'TinaMaidsTests' do
    inherit! :complete
    # Pods for testing
  end

  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
    
  target 'OneSignalNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.9.3', '< 3.0'
  end
    
end

target 'TinaMaids-tvOS' do
  # Pods for TinaMaids-tvOS

  target 'TinaMaids-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
